version: "3"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Shanghai
    volumes:
      - ${DOCKER_CONFIG}/sonarr:/config
      - ${DATA}/media/tv:/tv
      - ${DATA}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Shanghai
    volumes:
      - ${DOCKER_CONFIG}/radarr:/config
      - ${DATA}/media/movies:/movies
      - ${DATA}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Shanghai
    volumes:
      - ${DOCKER_CONFIG}/lidarr:/config
      - ${DATA}/media/music:/music
      - ${DATA}/downloads:/downloads  
    ports:
      - 8686:8686
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true
    volumes:
      - ${DOCKER_CONFIG}/jackett:/config
      - ${DATA}/downloads/etc:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - ${DOCKER_CONFIG}/qbittorrent:/config
      - ${DATA}/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Shanghai
    volumes:
      - ${DOCKER_CONFIG}/jellfin:/config
      - ${DOCKER_CONFIG}/fonts:/usr/share/fonts/
      - ${DATA}/media/tv:/data/tvshows
      - ${DATA}/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
  emby:
    image: linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Shanghai
    volumes:
      - ${DOCKER_CONFIG}/emby:/config
      - ${DATA}/media/tv:/data/tvshows
      - ${DATA}/media/movies:/data/movies
    ports:
      - 8098:8096
      - 8922:8920 #optional
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    volumes:
      - ${DATA}:/srv/data
      - ${DOCKER_CONFIG}:/srv/config
      - ${DOCKER_CONFIG}/filebrowser/filebrowser.db:/database/filebrowser.db
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
    ports:
      - 8002:80
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Shanghai
    volumes:
      - ${DOCKER_CONFIG}/heimdall:/config
    ports:
      - 8001:80
      - 8443:443
    restart: unless-stopped
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - 8000:80
      - 81:81
      - 443:443
    volumes:
      - ${DOCKER_CONFIG}/npm/data:/data
      - ${DOCKER_CONFIG}/npm/letsencrypt:/etc/letsencrypt
