version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Shanghai
    volumes:
      - ${DOCKER_CONFIG}/sonarr:/config
      - ${DATA}/media/tv:/tv
      - ${DATA}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Shanghai
    volumes:
      - ${DOCKER_CONFIG}/radarr:/config
      - ${DATA}/media/movies:/movies
      - ${DATA}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true
    volumes:
      - ${DOCKER_CONFIG}/jackett:/config
      - ${DATA}/downloads/etc:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - ${DOCKER_CONFIG}/qbittorrent:/config
      - ${DATA}/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
  